# CUSTOMERS CALLS #
@base_URL=http://localhost:5000/api/customers


get {{base_URL}}
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGNkMWZmODJlMzEyMWQ0M2IzYmYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjg0ODg0Njg5fQ.FbUqOk8kCUkrMWWO0upGowajITrBy2R6IvM6iFW0n9A
###
@objId1=646bb6339c1ac02e35e19755
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "name": "vince", 
    "address": "hillesteenweg 18",
    "phone": "0485/784459",
    "email": "vince123@gmail.com",
    "password": "vince123"
}

###
@objId2=646d4ef74638a3749a186169
put {{base_URL}}/{{objId2}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGVkMDQ2MzhhMzc0OWExODYxNjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjg0ODg1MjAxfQ.LLpI8tehGutqxHfIYOQ4dgKOUUVpHNPdGcI8on2wr5E

{
    "name": "vidddnce", 
    "address": "hilledsteenweg 19",
    "phone": "0485/784459",
    "email": "vincevddd@gmail.com",
    "password": "vince123"
}

###

@objId2=646d4ef74638a3749a186169
put {{base_URL}}/changeToAdmin/{{objId2}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI

{
    "name": "vince", 
    "address": "hilledsteenweg 19",
    "phone": "0485/784459",
    "email": "vincevdd@gmail.com",
    "password": "vince123"
}

###
@objId3=646bb6339c1ac02e35e19755
delete {{base_URL}}/{{objId3}}
Content-Type: application/json  
