# CUSTOMERS CALLS #
@base_URL=http://localhost:3000/api/drinks

get {{base_URL}}

###
@objId1=646b4fa4472f1e1a52a464fe
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "name": "Ice Tea", 
    "price": 4.99,
    "amountInStock": 12
}

###
@objId2=646b4fa4472f1e1a52a464fe
put {{base_URL}}/{{objId2}}
Content-Type: application/json

{
    "name": "Cola", 
    "price": 2.99,
    "amountInStock": 2
}

###
@objId3=646b4fa4472f1e1a52a464fe
delete {{base_URL}}/{{objId3}}
Content-Type: application/json  
