# CUSTOMERS CALLS #
@base_URL=http://localhost:3000/api/orders

get {{base_URL}}

###
@objId1=646baca50c5eaf4b329c1c83
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "sandwiches": ["646b4f90472f1e1a52a464f8", "646b4f94472f1e1a52a464fa"], 
    "drinks": ["646b53eb463ea788fabcf01d", "646b53ee463ea788fabcf01f"],
    "customer": "646b53de463ea788fabcf015",
    "deliverDate": "2023/5/23"
}
