# CUSTOMERS CALLS #
@base_URL=http://localhost:5000/api/orders

get {{base_URL}}

###
@objId1=646baca50c5eaf4b329c1c83
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI

{
    "sandwiches": ["646e3cf8b072cef9146ae2ba"], 
    "drinks": ["646b53eb463ea788fabcf01d", "646b53ee463ea788fabcf01f"],
    "customer": "646e3886513f6f4fdcf443ab",
    "deliverDate": "2023/5/23"
}
