# CUSTOMERS CALLS #
@base_URL=http://localhost:5000/api/sandwiches

get {{base_URL}}

###
@objId1=646bb67fe0e6b6f96dfad6a6
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI

{
    "name": "Baguette", 
    "price": 18,
    "ingredients": ["Garnaalsalade", "Sla", "Ei", "Tomaat"]
}

###
@objId2=646bb67fe0e6b6f96dfad6a6
put {{base_URL}}/{{objId2}}
Content-Type: application/json

{
    "name": "Broodje garnaalsalade",
    "price": "6.45",
    "ingredients": [
    "Garnaalsalade",
    "Sla",
    "Ei",
    "Tomaat",
    "Kaas"
  ]
}

###
@objId3=646bb67fe0e6b6f96dfad6a6
delete {{base_URL}}/{{objId3}}
Content-Type: application/json  
