# CUSTOMERS CALLS #
@base_URL=http://localhost:3000/api/sandwiches

get {{base_URL}}

###
@objId1=626fb3810a6e8b97afc297b8
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json

{
    "name": "Broodje garnaalsalade", 
    "price": "4.99",
    "ingredients": ["Garnaalsalade", "Sla", "Ei", "Tomaat"]
}

###
@objId2=6469df8715420e1265ffad18
put {{base_URL}}/{{objId2}}
Content-Type: application/json

{
    "name": "mario",
    "address": "torenstraat 48",
    "phone": "0485/55.55.55"
}

###
@objId3=6469df466f7d3138e519652c
delete {{base_URL}}/{{objId3}}
Content-Type: application/json  
