@base_URL=http://localhost:5000/api/sandwiches

get {{base_URL}}

###
@objId1=646e6cfad35fb5cbb10530cc
get {{base_URL}}/{{objId1}}
Content-Type: application/json

###
post {{base_URL}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI

{
    "name": "Broodje Smos", 
    "price": 3.99,
    "ingredients": ["Kaas", "Hesp", "Sla", "Ei", "Tomaat", "Mayonaise"]
}

###
@objId2=6477b0a99cdeff8d18c6a505
put {{base_URL}}/{{objId2}}
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI

{
    "name": "Broodje salami",
    "price": "6.45",
    "ingredients":  [
      "Salami pikant",
      "Sla",
      "Ei",
      "Tomaat",
      "Mayonaise"
    ]
}

###
@objId3=646e6cfad35fb5cbb10530cc
delete {{base_URL}}/{{objId3}}
Content-Type: application/json  
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZkNGZhNDQ2MzhhMzc0OWExODYxNzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ4ODU0NjJ9.Ihp_v0JkcwQHDCybTIUOdWLvO-LB6BsPdYgo9lL83yI
